# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
